-- SELECT DISTINCT rental_rate FROM film;
-- SELECT DISTINCT replacement_cost FROM film;
-- SELECT DISTINCT replacement_cost, rental_rate FROM film;
-- SELECT COUNT(*) FROM actor WHERE first_name = 'Penelope'; --> 4
-- SELECT COUNT(*) FROM actor WHERE first_name LIKE 'A%'; --> 13
-- SELECT COUNT(first_name) FROM actor WHERE first_name LIKE 'A%'; --> 13
-- SELECT COUNT(DISTINCT first_name) FROM actor;
-- SELECT COUNT(DISTINCT length) FROM film;