-- SELECT country FROM country WHERE country LIKE 'A%a';
-- SELECT country, LENGTH(country) FROM country WHERE LENGTH(country) >= 6 AND country LIKE '%n';
-- SELECT title FROM film WHERE LOWER(title) ILIKE '%t%t%t%t%';
-- SELECT * FROM film WHERE title LIKE 'C%' AND length > 90 and rental_rate = 2.99;
